### ISSUE TITLE
Importer: Format names are still in German, replace by better names

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#170]
suggestions:

"Neue Lieferketten Datei" -> "EFSA Format"
"Neue BfR-Lieferketten Datei" -> "BfR Format (single/multi version)"
"Excel Datei" -> What is this for?

**Comment by draaw** [comment]
done

**Comment by thoens** [comment]
"General Excel Importer" still exists. What is it used for?
I tried to import a random Excel file and nothing happened

**Comment by draaw** [comment]
"General Excel Importer"  imports tables one-to-one into the db. They need to provide the same scheme as the db tables have, for an example look at an exported Excel table - the format is identical.
